name: flutter_svg_example
description: An SVG samnple app.
homepage: https://github.com/dnfield/flutter_svg
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_svg:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/w3samples/
    - assets/deborah_ufw/
    - assets/simple/
    - assets/wikimedia/
    - assets/android_vd/

environment:
  sdk: '>=2.17.0-0 <3.0.0'
  flutter: ">=3.3.0-0"

dependency_overrides:
  vector_graphics:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
  vector_graphics_codec:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics_codec
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
  vector_graphics_compiler:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics_compiler
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
