name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
version: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.0.0+1
  vector_graphics_codec: ^1.0.0+1
  vector_graphics_compiler: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.18.0-0 <3.0.0'
  flutter: ">=3.3.0-0"

dependency_overrides:
  vector_graphics:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
  vector_graphics_codec:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics_codec
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
  vector_graphics_compiler:
    git:
      url: https://github.com/WinTicket/vector_graphics.git
      path: packages/vector_graphics_compiler
      ref: c1e8dd2a2e6a733ed4f503d01689c21636fc6a15
